# Generated by Django 3.2.18 on 2023-04-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'social media url'},
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='name',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='description',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(default='te', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='pinterest',
            field=models.CharField(default='te', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(default='te', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
