# Generated by Django 3.2.18 on 2023-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20230430_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='pinterest',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
    ]
