# Generated by Django 3.2.18 on 2023-04-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20230430_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social media url'},
        ),
    ]
