# Generated by Django 3.2.18 on 2023-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_socialmedia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default=' ', max_length=255, unique=True)),
                ('email', models.CharField(default=' ', max_length=255, unique=True)),
                ('address', models.CharField(default=' ', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts infromation',
            },
        ),
    ]
