# Generated by Django 3.2.18 on 2023-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Sweater', 'Sweater'), ('Dress', 'Dress'), ('Hoodies', 'Hoodies'), ('T-shirt', 'T-shirt'), ('Shorts', 'Shorts'), ('Skirt', 'Skirt'), ('Jeans', 'Jeans'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Shirt', 'Shirt'), ('Scarf', 'Scarf'), ('Jacket', 'Jacket')], max_length=50, null=True),
        ),
    ]
