# Generated by Django 3.2.18 on 2023-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20230322_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'winter'), (2, 'summer'), (3, 'springing'), (4, 'autumn')], max_length=50, null=True),
        ),
    ]
