# Generated by Django 3.2.18 on 2023-03-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20230322_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
