# Generated by Django 3.2.18 on 2023-03-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_rename_category_name_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collections'),
        ),
    ]
