# Generated by Django 3.2.18 on 2023-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_products_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
