# Generated by Django 3.2.18 on 2023-03-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20230322_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='C:\\Users\\omarh\\OneDrive\\Desktop\\test\\project\\image'),
        ),
        migrations.AddField(
            model_name='products',
            name='Color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.colors'),
        ),
    ]
