# Generated by Django 3.2.18 on 2023-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20230323_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
