# Generated by Django 3.2.18 on 2023-03-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20230327_0516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
