# Generated by Django 3.2.18 on 2023-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_products_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='data_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
