# Generated by Django 3.2.18 on 2023-04-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_products_data_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collection.products')),
            ],
        ),
    ]
