# Generated by Django 3.2.18 on 2023-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_stocko'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocko',
            old_name='count',
            new_name='L_count',
        ),
        migrations.AddField(
            model_name='stocko',
            name='S_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocko',
            name='XL_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocko',
            name='XXL_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
