# Generated by Django 3.2.18 on 2023-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_categories_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='product_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
