# Generated by Django 3.2.18 on 2023-04-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_collections_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocko',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocko', to='collection.products'),
        ),
    ]
