# Generated by Django 3.2.18 on 2023-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_alter_stocko_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='dis_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='in_showen',
            field=models.BooleanField(default=False),
        ),
    ]
