# Generated by Django 3.2.18 on 2023-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_rename_dis_img_promocode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ManyToManyField(to='collection.Collections'),
        ),
    ]
