# Generated by Django 3.2.18 on 2023-04-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_auto_20230430_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='products',
            field=models.ManyToManyField(to='collection.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='collection',
            field=models.ManyToManyField(related_name='product_collection', to='collection.Collections'),
        ),
    ]
