# Generated by Django 3.2.18 on 2023-04-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_auto_20230430_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='products',
        ),
        migrations.AlterField(
            model_name='products',
            name='collection',
            field=models.ManyToManyField(to='collection.Collections'),
        ),
    ]
