# Generated by Django 3.2.18 on 2023-04-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0032_auto_20230430_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fabric',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
