# Generated by Django 3.2.18 on 2023-04-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0033_products_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
