# Generated by Django 3.2.18 on 2023-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_promocode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
