# Generated by Django 3.2.18 on 2023-05-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_auto_20230505_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_color',
            new_name='Stockcolors',
        ),
    ]
