# Generated by Django 3.2.18 on 2023-05-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0037_rename_stock_color_stockcolors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock_color',
        ),
        migrations.AddField(
            model_name='stockcolors',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockcolors', to='collection.products'),
        ),
    ]
