# Generated by Django 3.2.18 on 2023-05-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0038_auto_20230505_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocko',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocko', to='collection.products', unique=True),
        ),
    ]
