# Generated by Django 3.2.18 on 2023-05-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_alter_stocko_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocko',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocko', to='collection.products'),
        ),
        migrations.DeleteModel(
            name='Stockcolors',
        ),
    ]
