# Generated by Django 3.2.18 on 2023-05-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0040_auto_20230506_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.PositiveIntegerField(default=0)),
                ('color_name', models.CharField(max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockcolor', to='collection.products')),
            ],
        ),
    ]
