# Generated by Django 3.2.18 on 2023-05-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0043_stockcolor_avail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocko',
        ),
    ]
