# Generated by Django 3.2.18 on 2023-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0044_delete_stocko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
