# Generated by Django 3.2.18 on 2023-03-27 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.TimeField(default=datetime.datetime(2023, 3, 27, 5, 27, 36, 137388)),
        ),
    ]
