# Generated by Django 3.2.18 on 2023-03-27 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0002_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 3, 32, 0, 297256, tzinfo=utc)),
        ),
    ]
