# Generated by Django 3.2.18 on 2023-04-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_order_transacation'),
        ('product_page', '0005_alter_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login.customer'),
        ),
    ]
