# Generated by Django 3.2.18 on 2023-04-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0006_reviews_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Customer',
            new_name='customer',
        ),
    ]
