# Generated by Django 3.2.18 on 2023-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1680899595.549297, max_length=100, null=True),
        ),
    ]
