# Generated by Django 3.2.18 on 2023-04-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20230408_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1680957713.903017, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsummary',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.orderitem'),
        ),
    ]
