# Generated by Django 3.2.18 on 2023-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20230408_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsummary',
            name='quantity_total',
        ),
        migrations.AddField(
            model_name='productsummary',
            name='total_quantity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1680958905.489516, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsummary',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
