# Generated by Django 3.2.18 on 2023-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20230408_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681008341.134661, max_length=100, null=True),
        ),
    ]
