# Generated by Django 3.2.18 on 2023-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_order_transacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='on_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681036065.932821, max_length=100, null=True),
        ),
    ]
