# Generated by Django 3.2.18 on 2023-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20230409_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681322265.561152, max_length=100, null=True),
        ),
    ]
