# Generated by Django 3.2.18 on 2023-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20230413_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681406937.147272, max_length=100, null=True),
        ),
    ]
