# Generated by Django 3.2.18 on 2023-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681407706.17002, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductTotal',
        ),
    ]
