# Generated by Django 3.2.18 on 2023-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20230413_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681408211.80949, max_length=100, null=True),
        ),
    ]
