# Generated by Django 3.2.18 on 2023-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_alter_order_transacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage_area',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681504002.707608, max_length=100, null=True),
        ),
    ]
