# Generated by Django 3.2.18 on 2023-04-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20230416_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681609188.359985, max_length=100, null=True),
        ),
    ]
