# Generated by Django 3.2.18 on 2023-04-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681609662.64523, max_length=100, null=True),
        ),
    ]
