# Generated by Django 3.2.18 on 2023-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_auto_20230416_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681609891.177251, max_length=100, null=True),
        ),
    ]
