# Generated by Django 3.2.18 on 2023-04-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_alter_order_transacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681610017.578534, max_length=100, null=True),
        ),
    ]
