# Generated by Django 3.2.18 on 2023-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_auto_20230416_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681696276.655446, max_length=100, null=True),
        ),
    ]
