# Generated by Django 3.2.18 on 2023-04-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_alter_promocode_discount'),
        ('login', '0043_alter_order_transacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681705287.621839, max_length=100, null=True),
        ),
    ]
