# Generated by Django 3.2.18 on 2023-04-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_auto_20230417_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='on_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pending',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendin', 'pendin'), ('on_delivery', 'on_delivery'), ('finish', 'finish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681756511.076846, max_length=100, null=True),
        ),
    ]
