# Generated by Django 3.2.18 on 2023-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_auto_20230417_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681762188.429692, max_length=100, null=True),
        ),
    ]
