# Generated by Django 3.2.18 on 2023-04-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1681880944.032764, max_length=100, null=True),
        ),
    ]
