# Generated by Django 3.2.18 on 2023-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0053_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1682445434.711447, max_length=100, null=True),
        ),
    ]
