# Generated by Django 3.2.18 on 2023-04-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0071_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1682812539.500117, max_length=100, null=True),
        ),
    ]
