# Generated by Django 3.2.18 on 2023-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0072_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1682817629.718376, max_length=100, null=True),
        ),
    ]
