# Generated by Django 3.2.18 on 2023-05-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0092_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1683327039.021687, max_length=100, null=True),
        ),
    ]
