# Generated by Django 3.2.18 on 2023-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0093_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1683329214.562907, max_length=100, null=True),
        ),
    ]
