# Generated by Django 3.2.18 on 2023-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0095_alter_order_transacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transacation',
            field=models.CharField(default=1683358954.962183, max_length=100, null=True),
        ),
    ]
