# Generated by Django 3.2.18 on 2023-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0097_auto_20230506_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transacation',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pendin', 'pendin'), ('on_delivery', 'on_delivery'), ('finish', 'finish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selectedcolor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selectedsize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
