# Generated by Django 3.2.18 on 2023-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='colors',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
