# Generated by Django 3.2.18 on 2023-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('All_About_Company', models.TextField()),
                ('journey', models.TextField()),
                ('who', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('Money_Back', models.TextField()),
                ('Customer_Service', models.TextField()),
                ('Free_Shipping', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
