# Generated by Django 3.2.18 on 2023-05-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
