# Generated by Django 3.2.18 on 2023-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0045_alter_categories_product_img'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='best_seller_products',
        ),
        migrations.AddField(
            model_name='index',
            name='best_seller_products',
            field=models.ManyToManyField(blank=True, to='collection.Products'),
        ),
    ]
