# Generated by Django 3.2.18 on 2023-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0045_alter_categories_product_img'),
        ('index', '0002_auto_20230508_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='featured', to='collection.Products'),
        ),
        migrations.AlterField(
            model_name='index',
            name='best_seller_products',
            field=models.ManyToManyField(blank=True, related_name='best_sellers', to='collection.Products'),
        ),
    ]
